### PR TITLE
Fix issue #2

### LINKED ISSUE #2: It does not work
Thank you for your help.
default

### PR DESCRIPTION
**Pull request by winterthediplomat**
This PR updates the code that uploads the files to imgur: the v3 version of the imgur API is now used.

A minor fix about a missing proxy has been added too (it would crash because of a missing parameter).

Written to fix #2

### CODE REVIEW

File: SauceNao-Windows/Program.cs [hunk 1]
```diff
@@ -23,8 +24,10 @@ class Program {
       string   SAUCENAO_API_KEY = args[0];
       string   IMGUR_API_KEY    = args[1];
       string   IMAGE_PATH       = args[2];
-      WebProxy PROXY            = args.Length >= 3 ? new WebProxy(args[3]) : null;
+      //fix: if proxy is not present, args[3] does not exist.
```
Comment (RoxasShadow) [inline SauceNao-Windows/Program.cs]: can we remove this line?

**Review by RoxasShadow — CHANGES_REQUESTED** [review]

**Comment by RoxasShadow** [comment]
So, it seems that #2 is related to some proxy issue in the application. I'll merge this soon as it makes it work as it is and then we can find a way to make the proxy work.

**Review by RoxasShadow — APPROVED** [review]

File: SauceNao-Windows/Program.cs (hunk 1 above)
Comment (winterthediplomat) [reply SauceNao-Windows/Program.cs]: removed, see last commit. good you catched it :D
